export const questions:string[] = [
    'während dem Sex mit Haushaltsgegenständen experimentiert.',
    'mehr als 3 Tage im Krankenhaus verbracht.',
    'im Schlaf gesabbert.',
    'mehr als eine Woche im Krankenhaus verbracht.',
    'ein gebrochenes Herz gehabt.',
    'meinem Partner das Frühstück ans Bett gebracht.',
    'gehofft, mein Partner wäre etwas offener in Sachen Sex.',
    'mit meinem Partner geschlafen, nur weil er es wollte.',
    'ein Date gehabt, nur um einer anderen Person wehzutun.',
    'was mit einem Austauschstudierenden gehabt.',
    'einer Person gesagt, dass ich sie liebe.',
    'unter der Dusche gesungen.',
    'eine Krankheit vorgetäuscht.',
    'nach Nacktfotos einer bestimmten Person im Internet gesucht.',
    'jemanden aus Wut lausthals angeschrien.',
    'eine Bong geraucht.',
    'jemanden vom gleichen Geschlecht auf sexuelle Weise attraktiv gefunden.',
    'jemanden ausgezogen, während er schlief.',
    'eine Straftat begangen.',
    'ohne Verhütung mit einer fremden Person geschlafen.',
    'ein Konzert besucht.',
    'meinen Partner mit dem Namen eines Ex-Partners angesprochen.',
    'jemanden beim Pornos schauen erwischt.',
    'ein Buch für die Schule komplett durchgelesen.',
    'mehr als 10 verschiedene Sexstellungen ausprobiert.',
    'im Schlaf geredet.',
    'einer fremden Person auf der Straße geholfen.',
    'mit einer elektrischen Zahnbürste onaniert.',
    'versucht an das Passwort einer anderen Person zu kommen.',
    'einen Sex-Ratgeber gelesen.',
    'aus Eifersucht eine Szene gemacht.',
    'eine Affäre mit einer verheirateten Person gehabt.',
    'etwas aus einem Hotelzimmer mitgehen lassen.',
    'etwas aus dem Bauchnabel einer anderen Person getrunken.',
    'einen Geschlechtsakt gehabt, der länger als drei Stunden gedauert hat.',
    'nach einem Horrorfilm das ganze Haus abgesucht.',
    'einen ganzen Tag lang geweint.',
    'einen Strafzettel bekommen.',
    'Unterwäsche vom anderen Geschlecht getragen.',
    'nach einem Besuch beim Friseur geweint.',
    'einen besonderen Menschen verloren.',
    'ein Auto gefahren, mit dem ich nicht hätte fahren dürfen.',
    'vergessen meine Pille zu nehmen.',
    'Sex mit einem Vorgesetzen oder Lehrer gehabt.',
    'jemandem gesagt, dass ich seinen Körper schön finde.',
    'auf einer Party geweint.',
    'etwas geschluckt, das ich nie wieder freiwillig schlucken würde.',
    'für jemanden gekocht.',
    'mich in meinen besten Freund verliebt.'
];